apiVersion: v1
kind: Service
metadata:
  name: {{ include "nakama-helm-chart.fullname" . }}-db
  labels:
    service: db
spec:
  type: ClusterIP
  ports:
  - port: 26257
    targetPort: 26257
    name: grpc
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nakama-helm-chart.fullname" . }}-nakama-loadbalancer
  labels:
    service: nakama
spec:
  selector:
    app: {{ include "nakama-helm-chart.fullname" . }}-nakama
  type: LoadBalancer
  ports:
  - port: 7350
    targetPort: 7350
    name: api
  - port: {{ .Values.nakama.adminport }}
    targetPort: 7351
    name: devapi
  - port: 7349
    targetPort: 7349
    name: grpc
  - port: 7348
    targetPort: 7348
    name: devgrpc